# Generated by Django 4.1 on 2022-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
