# Generated by Django 4.1 on 2022-08-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
