# Generated by Django 4.1 on 2022-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
