# Generated by Django 4.1 on 2022-08-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_board_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
