# Generated by Django 4.1 on 2022-08-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_board_hits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='hits',
            new_name='hit',
        ),
    ]
