# Generated by Django 4.1 on 2022-08-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_hits_board_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='hit',
        ),
        migrations.AddField(
            model_name='board',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
